### ISSUE TITLE
关于无法在平板上获取章节列表

### ISSUE THREAD

**Issue by killerquee** [LittleStar-OuO/plugin.CopyManga#1]
如题，在电脑上可以正常工作，但是在我的小米平板上无法打开章节列表
可以正常打开插件，但是点开之后看不到章节列表，章节列表是空白的
![屏幕截图 2024-01-28 170051](https://github.com/RuliaReader/plugin.CopyManga/assets/58289940/d69f5283-984d-427c-8afe-a53430dac5f2)
在平板上看不到章节列表下面的东西
平板系统是完整版的win11
电脑上是win10，不知道是否与此有关

**Comment by LittleStar-OuO** [comment]
试试其他插件正不正常？如果不正常的话需要反馈给Rulia作者，而不是插件作者

**Comment by LittleStar-OuO** [comment]
我更建议进QQ群反馈，插件作者和Rulia作者都在群里，群号：623730051
