### ISSUE TITLE
[Bug Report]搜索不可用

### ISSUE THREAD

**Issue by Jiang10086** [LittleStar-OuO/plugin.CopyManga#2]
例如首页有推荐[《子彈才不會進到鍋里來》](https://www.mangacopy.com/comic/zidancaibuhuijingdaoguolilai)，但搜索無法搜到
![image](https://github.com/RuliaReader/plugin.CopyManga/assets/67213568/ba48fa3a-aa73-4954-a8a3-7749d5884110)
![image](https://github.com/RuliaReader/plugin.CopyManga/assets/67213568/00503451-064f-4312-aa20-827f3fc56fb6)

**Comment by LittleStar-OuO** [comment]
![image](https://github.com/RuliaReader/plugin.CopyManga/assets/66309524/1166a658-e8be-497d-acf7-33017281d428)
有没有可能，搜简体就行了（我网不太行，封面还没加载出来请忽略）
